### ISSUE TITLE
error in basic s2v conversion since from 2.7.0-2.7.1

### ISSUE THREAD

**Issue by rumburake** [Ashung/svg2vectordrawable#57]
This is how `s2v` works correctly in v2.6.5. It turns a SVG into XML:

```
root@37b7bdf1843c:~# yarn global add svg2vectordrawable@2.6.5
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "svg2vectordrawable@2.6.5" with binaries:
      - s2v
      - svg2avd
      - svg2android
      - svg2vector
      - svg2drawable
      - svg2vectordrawable
Done in 1.87s.
root@37b7bdf1843c:~# s2v -i foo.svg -o boo.xml
∙ foo.svg → boo.xml
```
In v2.7.0 this is broken and can't be run at all:

```
root@37b7bdf1843c:~# yarn global add svg2vectordrawable@2.7.0
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "svg2vectordrawable@2.7.0" with binaries:
      - s2v
      - svg2avd
      - svg2android
      - svg2vector
      - svg2drawable
      - svg2vectordrawable
Done in 3.17s.
root@37b7bdf1843c:~# s2v -i foo.svg -o boo.xml
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../lib/coa'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/svg2vectordrawable/bin/svg2vectordrawable:3:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

From v.2.7.1 this was fixed, but now it gives error if we don't specify `floatPrecision`:
```
root@37b7bdf1843c:~# yarn global add svg2vectordrawable@2.7.1
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "svg2vectordrawable@2.7.1" with binaries:
      - s2v
      - svg2avd
      - svg2android
      - svg2vector
      - svg2drawable
      - svg2vectordrawable
Done in 1.91s.
root@37b7bdf1843c:~# s2v -i foo.svg -o boo.xml
TypeError: Cannot read property 'floatPrecision' of undefined
    at module.exports.convertFile (/usr/local/share/.config/yarn/global/node_modules/svg2vectordrawable/src/svg-file-to-vectordrawable-file.js:53:33)
    at svgFiles.forEach.svgFile (/usr/local/share/.config/yarn/global/node_modules/svg2vectordrawable/src/coa.js:223:24)
    at Array.forEach (<anonymous>)
    at Cmd.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/svg2vectordrawable/src/coa.js:213:22)
    at Q.when.prev (/usr/local/share/.config/yarn/global/node_modules/coa/lib/cmd.js:417:45)
    at _fulfilled (/usr/local/share/.config/yarn/global/node_modules/q/q.js:854:54)
    at /usr/local/share/.config/yarn/global/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/usr/local/share/.config/yarn/global/node_modules/q/q.js:816:13)
    at /usr/local/share/.config/yarn/global/node_modules/q/q.js:624:44
    at runSingle (/usr/local/share/.config/yarn/global/node_modules/q/q.js:137:13)
```

However if we add explicitly the precision parameter there's another error:
```
root@37b7bdf1843c:~# s2v -p 2 -i foo.svg -o boo.xml
Error outputFile is not defined while converting file foo.svg
```

To fix that we would need to change `outputFile` in function `convertFile` to `module.exports.outputFile` - in `svg-file-to-vectordrawable-file.js`

**Comment by rumburake** [comment]
In fact it works fine in all versions up to and including `v2.6.26`. But broken since `v2.7.0`
